# This file was generated by GoReleaser. DO NOT EDIT.
cask "autodevelop" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "b98fa62018fcc59ce93053865366b155ddb1991abd1a13dd8579545ca88d1ec5"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_darwin_arm64"
      binary "autodevelop_0.1.5_darwin_arm64", target: "autodevelop"
    end
    on_intel do
      sha256 "cdf99ba16cf2e2c0477b6e1f25a024558e09f431f784d049b1e2afa2270d2019"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_darwin_amd64"
      binary "autodevelop_0.1.5_darwin_amd64", target: "autodevelop"
    end
  end
  on_linux do
    on_arm do
      sha256 "c0a1b6af00bad15f5890feefeab42611573f8b47f121a3e43d9dff9035a92b6c"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_linux_arm64"
      binary "autodevelop_0.1.5_linux_arm64", target: "autodevelop"
    end
    on_intel do
      sha256 "4bfdff3a07bca1cb96734d304d17690b29dd9eb5fcfa33287a7dabc3555a95fb"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_linux_amd64"
      binary "autodevelop_0.1.5_linux_amd64", target: "autodevelop"
    end
  end

  name "autodevelop"
  desc "Autodevelop CLI — login, kit install, and MCP for agentic coding teams."
  homepage "https://github.com/devrecated/autodevelop-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
