# This file was generated by GoReleaser. DO NOT EDIT.
cask "autodevelop" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "7583ad5acbe3b9f05f6c5e6023d0f03e9cd4f1ee3cc046ed8a7e8eef8ab81fae"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_darwin_arm64"
      binary "autodevelop_0.1.4_darwin_arm64", target: "autodevelop"
    end
    on_intel do
      sha256 "379fc6793b1b751fcde9a8401d2566a31f2b00a566ce821831bfc52b34dd3364"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_darwin_amd64"
      binary "autodevelop_0.1.4_darwin_amd64", target: "autodevelop"
    end
  end
  on_linux do
    on_arm do
      sha256 "4150f86f09f79ba5d1498ddecbec14bb59cf068eea0ba2120c9cf94d0f484bd4"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_linux_arm64"
      binary "autodevelop_0.1.4_linux_arm64", target: "autodevelop"
    end
    on_intel do
      sha256 "ddfbe4b5cac9ad989b505bb10df206fe4373920fe42c991dd70e10d697a3a3fb"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_linux_amd64"
      binary "autodevelop_0.1.4_linux_amd64", target: "autodevelop"
    end
  end

  name "autodevelop"
  desc "Autodevelop CLI — login, kit install, and MCP for agentic coding teams."
  homepage "https://github.com/devrecated/autodevelop-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
