# This file was generated by GoReleaser. DO NOT EDIT.
cask "autodevelop" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "6b3f19888352adba30571d2db0d28a9e7a11c62eb99956acbe647281e932f8d8"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_darwin_arm64"
      binary "autodevelop_0.1.3_darwin_arm64", target: "autodevelop"
    end
    on_intel do
      sha256 "c67fef75fa23f3d2f04e832a0874dc4899c38a99d8190b134c8390981eaddc58"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_darwin_amd64"
      binary "autodevelop_0.1.3_darwin_amd64", target: "autodevelop"
    end
  end
  on_linux do
    on_arm do
      sha256 "c9d6dd45a16c70a2bebbd6dba073292b74bb84e2283762095d0b76fa58be8de3"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_linux_arm64"
      binary "autodevelop_0.1.3_linux_arm64", target: "autodevelop"
    end
    on_intel do
      sha256 "3c9095290369a10f55883a591b29792da34f62484d72bf72a46cd474a5fde598"
      url "https://github.com/devrecated/autodevelop-cli/releases/download/v#{version}/autodevelop_#{version}_linux_amd64"
      binary "autodevelop_0.1.3_linux_amd64", target: "autodevelop"
    end
  end

  name "autodevelop"
  desc "Autodevelop CLI — login, kit install, and MCP for agentic coding teams."
  homepage "https://github.com/devrecated/autodevelop-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
